from fastapi import FastAPI
from fastapi.responses import HTMLResponse

app = FastAPI()

@app.get("/example.json")
def example():
    return {"msg": "hello world",
            "answer_to_everything": 42}

@app.get("/index.html", response_class=HTMLResponse)
def index():
    return """
        <html>
         <body>
          <p>
           It works :)<br/>
           Here you find <a href="http://localhost:8000/example.json">some example json</a>
          <p>
          <p>
          Autogenerated API documentation is provided as 
          <a href="http://localhost:8000/openapi.json">openapi.json</a> and
          <a href="http://localhost:8000/docs"</a>Swagger UI</a>.
          </p>
         </body>
        </html>
    """


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app)
